name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Om-Pramod-Kumar
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin output || echo "No output branch yet"
          git switch output || git switch -c output
          cp dist/snake.svg .
          git add snake.svg
          git commit -m "Generated snake.svg" || echo "No changes to commit"
          git push origin output
