name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Om-Pramod-Kumar
          outputs: dist/snake.svg

      - name: Upload artifact (debugging)
        uses: actions/upload-artifact@v4
        with:
          name: snake-preview
          path: dist/snake.svg

      - name: Deploy Snake to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
